import Head from 'next/head'
import Image from 'next/image'
// import Slider from "react-slick";

import styles from '../styles/Home.module.css'
import imgs from "../public/campaign_img.png"




export default function Home() {
  return (
    <>
      <Head>
        <title>CrowdFunding Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />


        <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />

      </Head>


      <body>

        <div className={styles.header_section}>
          <div className="left_header">
            <p>Cmpny Name</p>
          </div>

          <div className="mid_header">
            <ul className={styles.mid_ul}>
              <li>Home</li>
              <li>About Us</li>
              <li>Help</li>

            </ul>


          </div>

          <div className="right_header">
            <p>SignUP/Login</p>
          </div>
        </div>



        





        <div className={styles.middle_part}>

          <p className={styles.middle_part_qsn}>
            What are we
          </p>

          <p className={styles.middle_part_ans}>
            A decentralized open-source crowdfunding/investing  <br /> platform whose  mission  is to change the rules of the game in the world of investments.


          </p>



        </div>



        {/* coding the Cards of Campagin part
         */}


        <p className={styles.campaign_section_p}>
          Running Campaigns

        </p>


        <div className={styles.campaign_section}>



          <div className={styles.all_campaign}>


            <div className={styles.campaign}>

              <div className={styles.campaign_img}>
                <img src={imgs} alt="some img" />
              </div>

              <div className={styles.campaign_title}>
                <p>
                  Crowd Funding For Nothing
                </p>

                <p className={styles.campaign_by}>
                  by Mr. Falcon
                </p>


              </div>


              <div className={styles.campaign_desc}>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, aperiam! Placeat rerum est hic quaerat delectus repellat corrupti sunt ex, pariatur eum illum, doloribus voluptas nemo ad maiores eius voluptates.
              </div>


              <div className={styles.campaign_lower_part}>

                <span>
                  0% <br />
                  Progress

                </span>

                <span>
                  0 ETH
                  <br />
                  Raised

                </span>

                <span>
                  69
                  <br />
                  days left
                </span>
              </div>

            </div>











            <div className={styles.campaign}>

              <div className={styles.campaign_img}>
                <img src="" alt="some img" />
              </div>

              <div className={styles.campaign_title}>
                <p>
                  Crowd Funding For Nothing
                </p>

                <p className={styles.campaign_by}>
                  by Mr. Falcon
                </p>


              </div>


              <div className={styles.campaign_desc}>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, aperiam! Placeat rerum est hic quaerat delectus repellat corrupti sunt ex, pariatur eum illum, doloribus voluptas nemo ad maiores eius voluptates.
              </div>


              <div className={styles.campaign_lower_part}>

                <span>
                  0% <br />
                  Progress

                </span>

                <span>
                  0 ETH
                  <br />
                  Raised

                </span>

                <span>
                  69
                  <br />
                  days left
                </span>
              </div>

            </div>















            <div className={styles.campaign}>

              <div className={styles.campaign_img}>
                <img src="" alt="some img" />
              </div>

              <div className={styles.campaign_title}>
                <p>
                  Crowd Funding For Nothing
                </p>

                <p className={styles.campaign_by}>
                  by Mr. Falcon
                </p>


              </div>


              <div className={styles.campaign_desc}>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, aperiam! Placeat rerum est hic quaerat delectus repellat corrupti sunt ex, pariatur eum illum, doloribus voluptas nemo ad maiores eius voluptates.
              </div>


              <div className={styles.campaign_lower_part}>

                <span>
                  0% <br />
                  Progress

                </span>

                <span>
                  0 ETH
                  <br />
                  Raised

                </span>

                <span>
                  69
                  <br />
                  days left
                </span>
              </div>

            </div>













          </div>




        </div>




        <div className={styles.footer}>

          this is Footer
        </div>




      </body>










    </>



  )
}
