import Head from 'next/head'
import Image from 'next/image'



import styles from '../styles/Home.module.css'
import imgs from "../public/campaign_img.png"





export default function Home() {
  return (
    <>
      <Head>
        <title>CrowdFunding Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />


        <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />

      </Head>


      <div className={styles.all}>

      






        





        <div className={styles.middle_part}>

          <p className={styles.middle_part_qsn}>
            What are we
          </p>

          <p className={styles.middle_part_ans}>
            A decentralized open-source crowdfunding/investing  <br /> platform whose  mission  is to change the rules of the game in the world of investments.


          </p>



        </div>



        {/* coding the Cards of Campagin part
         */}


        <p className={styles.campaign_section_p}>
          Running Campaigns

        </p>


        <div className={styles.campaign_section}>



          <div className={styles.all_campaign}>


            <div className={styles.campaign}>

              <div className={styles.campaign_img}>
                {/* <img src={imgs} alt="some img" /> */}

                <Image src={imgs} 
                 width={350}
                height={230} />

                
              </div>

              <div className={styles.campaign_title}>
                <p>
                  Crowd Fund raising for startip-2
                </p>

                <p className={styles.campaign_by}>
                  by Mr. Falcon
                </p>


              </div>


              <div className={styles.campaign_desc}>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, aperiam! Placeat rerum est hic quaerat delectus repellat corrupti sunt ex, pariatur eum illum, doloribus voluptas nemo ad maiores eius voluptates.
              </div>


              <div className={styles.campaign_lower_part}>

                <span>
                  5% <br />
                  Progress

                </span>

                <span>
                  2 ETH
                  <br />
                  Raised

                </span>

                <span>
                  6
                  <br />
                  days left
                </span>
              </div>

            </div>











            <div className={styles.campaign}>

              <div className={styles.campaign_img}>
              <Image src={imgs} 
                 width={350}
                height={230} />
              </div>

              <div className={styles.campaign_title}>
                <p>
                  Crowd Fundraising For Startup-2
                </p>

                <p className={styles.campaign_by}>
                  by Mr. Falcon
                </p>


              </div>


              <div className={styles.campaign_desc}>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, aperiam! Placeat rerum est hic quaerat delectus repellat corrupti sunt ex, pariatur eum illum, doloribus voluptas nemo ad maiores eius voluptates.
              </div>


              <div className={styles.campaign_lower_part}>

                <span>
                  10% <br />
                  Progress

                </span>

                <span>
                  5 ETH
                  <br />
                  Raised

                </span>

                <span>
                  9
                  <br />
                  days left
                </span>
              </div>

            </div>















            <div className={styles.campaign}>

              <div className={styles.campaign_img}>
              <Image src={imgs} 
                 width={350}
                height={230} />
              </div>

              <div className={styles.campaign_title}>
                <p>
                Crowd Fundraising For Startup-3
                </p>

                <p className={styles.campaign_by}>
                  by Mr. Falcon
                </p>


              </div>


              <div className={styles.campaign_desc}>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, aperiam! Placeat rerum est hic quaerat delectus repellat corrupti sunt ex, pariatur eum illum, doloribus voluptas nemo ad maiores eius voluptates.
              </div>


              <div className={styles.campaign_lower_part}>

                <span>
                  15% <br />
                  Progress

                </span>

                <span>
                  3 ETH
                  <br />
                  Raised

                </span>

                <span>
                  12
                  <br />
                  days left
                </span>
              </div>

            </div>













          </div>




        </div>




        <div className={styles.footer}>

          this is Footer
        </div>




      


</div>







    </>



  )
}
